### PR TITLE
Change the position of the contextual menu

### PR DESCRIPTION
**Pull request by JRaigoza**
Change the position of the contextual menu for large pages, the menu is lost when the page is really large

### CODE REVIEW

**Comment by Wildhoney** [comment]
Thanks @JRaigoza &mdash; I thought I'd fixed this previously.

```javascript
/*Please replace: scope.position = { x: event.clientX, y: event.clientY };*/
```

Do we need [this](https://github.com/Wildhoney/ngContextMenu/pull/19/files#diff-bfb9eff7e43264c74245f994d9195e64R123) line?

**Comment by Wildhoney** [comment]
Bump :+1: I'd like to merge this, but unsure why we need the comment.

**Comment by guswnsxodlf** [comment]
Plz merge this....

**Comment by Wildhoney** [comment]
Merged and released as `v0.7.0` 👍 Thanks @JRaigoza

**Comment by guswnsxodlf** [comment]
Thanks

**Comment by Wildhoney** [comment]
Thanks @guswnsxodlf

**Pull request merged**
